; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = inkplate5v2

[env:inkplate5v2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 460800
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv
build_flags = 
	-DARDUINO_INKPLATE5V2
	-DBOARD_HAS_PSRAM
monitor_filters = time, esp32_exception_decoder
lib_deps = 
	e-radionicacom/InkplateLibrary @ ^11.1.2
	bitbank2/unzipLIB @ ^1.0.0

[env:native]
platform = native
test_build_src = no
build_flags = -DTEST_NATIVE
lib_deps =
